###############################################################################
############################## INCLUDE #######################################
###############################################################################

include:
  - local: 'GitlabCI/jobs/node/test.gitlab-ci.yml'
  - local: 'GitlabCI/jobs/node/build.gitlab-ci.yml'

###############################################################################
########################### GLOBAL DEFINITION #################################
###############################################################################

cache:
  paths:
    - "${CI_PROJECT_DIR}/node_modules"

###############################################################################
######################## YAML ANCHOR DEFINITION ###############################
###############################################################################

.node_image: &node_image
   node:18 # Check version image for node jobs

###############################################################################
############################## JOBS CALL #######################################
###############################################################################

.node:test:
  extends: .test
  image: *node_image
  before_script:
    - echo "job $CI_JOB_NAME"

.node:build:
  extends: .build
  image: *node_image
  before_script:
    - echo "job $CI_JOB_NAME"
