variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${ENV}_state
  TF_VAR_environnement: ${ENV}

stages:
  - example

include:
  - local: 'Gitlab/env/example.gitlab-ci.yml'
